config/routes.rb
Rails.application.routes.draw do
  root to: 'tv_shows#index' 
  devise_for :users
  resources :tv_shows, only: [:index]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/tv_channel.rb
class TvChannel < ApplicationRecord
  has_many :tv_shows
end

app/models/tv_show.rb
class TvShow < ApplicationRecord
  belongs_to :tv_channel
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/tv_shows_controller.rb
class TvShowsController < ApplicationController
  
  def index
    if params[:search]
      @tv_shows = TvShow.where("name LIKE ?", "%#{params[:search]}%")&.order("created_at DESC")
    else
      @tv_shows = TvShow.all.order('created_at DESC')
    end
  end

  private
    def tv_show_params
      params.require(:tv_show).permit(:name, :timing, :tv_channel_id)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
  end 
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/tv_channels_helper.rb
module TvChannelsHelper
end

app/helpers/tv_shows_helper.rb
module TvShowsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_flash.html.erb
<div class = "flash-message">
  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NewTestApp</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render "layouts/flash" %>
    <div id="user_nav">
      <% if user_signed_in? %>
        Logged in as <strong><%= current_user.email %></strong>.
        <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %>
        <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
      <% else %>
        <%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'  %>
        <%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %>
      <% end %>
    </div>
    <%= yield %>
  </body>
</html>

app/views/tv_shows/index.html.erb
<%= form_tag tv_shows_path, :method => 'get'  do %>
  <%= text_field_tag :search, params[:search]%>
  <%= submit_tag "Search", :name => nil  %>
<% end %>

<div class= "welcome-home">
  <h1>TV Shows</h1>

  <table>
    <thead>
      <tr>
        <th>Name</th>
        <th>Timing</th>
        <th>TV-Channel</th>
      </tr>
    </thead>

    <tbody>
      <% @tv_shows.each do |tv_show| %>
        <tr>
          <td><%= tv_show.name %></td>
          <td><%= tv_show.timing %></td>
          <td><%= tv_show.tv_channel.name%></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>  